<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeMate.Contracts\CodeMate.Contracts.csproj" />
    <ProjectReference Include="..\CodeMate.Domain\CodeMate.Domain.csproj" />
    <ProjectReference Include="..\CodeMate.Shared\CodeMate.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Interfaces\" />
    <Folder Include="Projects\Mappings\" />
    <Folder Include="Projects\Validators\" />
    <Folder Include="Projects\Services\" />
    <Folder Include="Tasks\Mappings\" />
    <Folder Include="Tasks\Validators\" />
    <Folder Include="Tasks\Services\" />
    <Folder Include="Users\Mappings\" />
    <Folder Include="Users\Validators\" />
    <Folder Include="Users\Services\" />
  </ItemGroup>

</Project>
