<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Auth\**" />
    <Compile Remove="Projects\**" />
    <Compile Remove="Tasks\**" />
    <Compile Remove="Users\**" />
    <EmbeddedResource Remove="Auth\**" />
    <EmbeddedResource Remove="Projects\**" />
    <EmbeddedResource Remove="Tasks\**" />
    <EmbeddedResource Remove="Users\**" />
    <None Remove="Auth\**" />
    <None Remove="Projects\**" />
    <None Remove="Tasks\**" />
    <None Remove="Users\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CodeMate.Contracts\CodeMate.Contracts.csproj" />
    <ProjectReference Include="..\CodeMate.Domain\CodeMate.Domain.csproj" />
    <ProjectReference Include="..\CodeMate.Shared\CodeMate.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.2.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
  </ItemGroup>

</Project>
